import React, { useEffect, useState } from "react";
import { Container } from "react-bootstrap";
import Header from "../Header";
import AssessmentEndAlert from "../AssessmentEndAlert";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";
import ProgressProvider from "../ProgressProvider";
import axios from "axios";
import API_URLS from "../../API_URLS.json";

function AssessmentScoreC({ id, assessmentId }) {
  const [score, setScore] = useState(0);
  const [maxScore, setMaxScore] = useState(1);
  const [percentage, setPercentage] = useState(0);

  useEffect(() => {
    const getMarks = async () => {
      let data = {
        id: id,
        assessmentId: assessmentId,
      };
      axios
        .post(API_URLS["get_marks"], data, { withCredentials: true })
        .then((response) => {
          console.log((response.data.obtainedMarks / response.data.totalMarks) * 100)
          setScore(response.data.obtainedMarks);
          setMaxScore(response.data.totalMarks);
          setPercentage(
            (response.data.obtainedMarks / response.data.totalMarks) * 100
          );
        })
        .catch((error) => {
          console.log(error);
        });
      /* */
    };
    getMarks();
  });

  return (
    <div>
      <Container>
        <div className="py-5">
          <AssessmentEndAlert />
        </div>
        <div className="grade-info">
          <h1>Grade</h1>
          <div className="progress-style py-5">
            <CircularProgressbar
              value={percentage}
              text={`${percentage.toFixed(2)}%`}
              styles={buildStyles({
                textColor: "green",
                pathColor: "green",
              })}
            />
          </div>
          <div className="py-2">
            <h4 className="score">
              {score} Points out of {maxScore}
            </h4>
          </div>
          <div className="py-2">
            N.B: This score is auto-generated by the system. It can be revised
            by the evaluator.
          </div>
        </div>
      </Container>
    </div>
  );
}

export default AssessmentScoreC;
