# Generated by Django 4.0.6 on 2022-07-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evaluator',
            old_name='userId',
            new_name='user',
        ),
    ]
