# Generated by Django 4.0.6 on 2022-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0002_rename_userid_candidate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='MCQQuestion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oes.assessment'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='evaluatorsAnswer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='evaluatorsAnswerAudio',
            field=models.FileField(upload_to='MicroVivaAnswer/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='evaluatorsAnswerTEXT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='mvQuestionAudio',
            field=models.FileField(upload_to='MicroVivaQuestion/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='mvQuestionText',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='microvivasubmission',
            name='submittedAnswerAudio',
            field=models.FileField(upload_to='MicroVivaSubmission/%Y/%m/%d'),
        ),
    ]
