# Generated by Django 4.0.6 on 2022-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0003_assessment_ispublished_alter_mcq_mcqquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
