# Generated by Django 4.0.6 on 2022-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcohort',
            name='cohortName',
            field=models.CharField(max_length=32),
        ),
    ]
