# Generated by Django 4.0.6 on 2022-08-01 10:03

from django.db import migrations, models
import django.db.models.deletion
import oes.models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0005_alter_examcohort_cohortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='totalMarks',
            field=models.IntegerField(validators=[oes.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='totalTime',
            field=models.IntegerField(validators=[oes.models.validate_mcq_time]),
        ),
        migrations.AlterField(
            model_name='mcqchoice',
            name='mcq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oes.mcq'),
        ),
        migrations.AlterField(
            model_name='mcqsubmission',
            name='mcq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oes.mcq'),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oes.assessment'),
        ),
        migrations.AlterField(
            model_name='microviva',
            name='totalMarks',
            field=models.IntegerField(validators=[oes.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='microvivasubmission',
            name='mv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oes.microviva'),
        ),
    ]
