# Generated by Django 4.0.6 on 2022-08-01 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0006_alter_mcq_totalmarks_alter_mcq_totaltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqsubmission',
            name='submissionEndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqsubmission',
            name='submissionStartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microvivasubmission',
            name='submissionEndTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microvivasubmission',
            name='submissionStartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcqsubmission',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oes.mcqchoice'),
        ),
        migrations.AlterField(
            model_name='mcqsubmission',
            name='obtainedMarks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='microvivasubmission',
            name='obtainedMarks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='microvivasubmission',
            name='submittedAnswerAudio',
            field=models.FileField(null=True, upload_to='MicroVivaSubmission/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='microvivasubmission',
            name='submittedAnswerText',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
