# Generated by Django 4.0.6 on 2022-08-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0007_mcqsubmission_submissionendtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqsubmission',
            old_name='camdidate',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='microvivasubmission',
            old_name='camdidate',
            new_name='candidate',
        ),
    ]
