# Generated by Django 4.0.6 on 2022-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0010_alter_mcqsubmission_obtainedmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqchoice',
            name='choice',
            field=models.CharField(max_length=255),
        ),
    ]
