# Generated by Django 4.1.5 on 2023-01-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0011_alter_mcqchoice_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='questionGroup',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='oes.questiongroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microviva',
            name='questionGroup',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='oes.questiongroup'),
            preserve_default=False,
        ),
    ]
