# Generated by Django 4.1.5 on 2023-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0013_questiongroup_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microviva',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
