# Generated by Django 4.1.5 on 2023-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oes', '0014_mcq_created_at_microviva_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqsubmission',
            name='submittedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microvivasubmission',
            name='submittedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
